# Generated by Django 6.0.3 on 2026-03-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='interview_questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='quantification_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='red_flags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='seniority_level',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
